export const status = {
  REQUEST: 0,
  SUCCESS: 1,
  ERROR: 2,
};

export const apiResponsestatus = {
  SUCCESS: 1,
  FAILED: 0,
  AUTHFAILED: -1,
};

export const configurations = {
  ApiUrl: "http://122.170.10.70:8888/api",
};

export const getHeaders = {
  headers: {
    Authorization: "Bearer " + localStorage.getItem("token"),
  },
};

export const apiEndPoints = {
  loginUser: configurations.ApiUrl + "/User/LoginUser",
  getUserRights: configurations.ApiUrl + "/GetUserRights",
  getCountryList: configurations.ApiUrl + "/Country/CountryList",
  createCountry: configurations.ApiUrl + "/Country/CreateOrUpdateCountry",
  deleteCountry: configurations.ApiUrl + "/Country/DeleteCountry",
  createCity: configurations.ApiUrl + "/City/CreateOrUpdateCity",
  getCityList: configurations.ApiUrl + "/City/CityList",
  deleteCity: configurations.ApiUrl + "/City/DeleteCity",
  getStateList: configurations.ApiUrl + "/State/StateList",
  deleteState: configurations.ApiUrl + "/State/DeleteState",
  createState: configurations.ApiUrl + "/State/CreateOrUpdateState",
  getDefaultRights: configurations.ApiUrl + "/User/GetDefaultRights",
  createRole: configurations.ApiUrl + "/User/CreateOrUpdateRole",
  deleteRole: configurations.ApiUrl + "/User/DeleteRole",
  getRoles: configurations.ApiUrl + "/User/Rolelist",
  getSupplierList: configurations.ApiUrl + "/Supplier/SupplierList",
  deleteSupplier: configurations.ApiUrl + "/Supplier/DeleteSupplier",
  getSupplierItemList: configurations.ApiUrl + "/Supplier/SupplierItemList",
  getCardList: configurations.ApiUrl + "/Card/CardList",
  addCard: configurations.ApiUrl + "/Card/CreateOrUpdateCard",
  deleteCard: configurations.ApiUrl + "/Card/DeleteCard",
  getDistrictList: configurations.ApiUrl + "/District/DistrictList",
  createDistrict: configurations.ApiUrl + "/District/CreateOrUpdateDistrict",
  deleteDistrict: configurations.ApiUrl + "/District/DeleteDistrict",
  getItemList: configurations.ApiUrl + "/Item/ItemList",
  deleteItem: configurations.ApiUrl + "/Item/DeleteItem",
  addItem: configurations.ApiUrl + "/Item/CreateOrUpdateItem",
  getLocationList: configurations.ApiUrl + "/Location/LocationtList",
  deleteLocation: configurations.ApiUrl + "/Location/DeleteLocation",
  addLocation: configurations.ApiUrl + "/Location/CreateOrUpdateLocation",
  getItemGroup: configurations.ApiUrl + "/Item/AddItemDropDown",
  getProjectList: configurations.ApiUrl + "/Project/ProjectList",
  getDesignationList: configurations.ApiUrl + "/Designation/DesignationList",
  deleteDesignation: configurations.ApiUrl + "/Designation/DeleteDesignation",
  addDesignation:
    configurations.ApiUrl + "/Designation/CreateOrUpdateDesignation",
  getProjectMetaData: configurations.ApiUrl + "/Project/AddProjectDropDown",
  deleteProject: configurations.ApiUrl + "/Project/DeleteProject",
  addProject: configurations.ApiUrl + "/Project/CreateOrUpdateProject",
  getUserList: configurations.ApiUrl + "/User/GetAllUsers",
  addUser: configurations.ApiUrl + "/User/CreateOrUpdateUser",
  deleteUser: configurations.ApiUrl + "/User/DeleteUser",
  getVehicleList: configurations.ApiUrl + "/Vehicle/VehicleList",
  deleteVehicle: configurations.ApiUrl + "/Vehicle/DeleteVehicle",
  addVehicle: configurations.ApiUrl + "/Vehicle/CreateOrUpdateVehicle",
  getRoomList: configurations.ApiUrl + "/Room/RoomList",
  deleteRoom: configurations.ApiUrl + "/Room/DeleteRoom",
  addRoom: configurations.ApiUrl + "/Room/CreateOrUpdateRoom",
  addSupplier: configurations.ApiUrl + "/Supplier/CreateOrUpdateSupplier",
  getSupplierMetaList:
    configurations.ApiUrl + "/Supplier/AddSupplierMasterDropDown",
  getUserMetaList: configurations.ApiUrl + "/User/AddUserDropDown",
  getVehicleMetaList: configurations.ApiUrl + "/Vehicle/AddVehicleDropDown",
  getRoomMetaList: configurations.ApiUrl + "/Room/AddRoomDropDown",
  loginUserDropDown: configurations.ApiUrl + "/User/LoginUserDropDown",
  getEmployeeList: configurations.ApiUrl + "/User/GetAllEmployee",
  addEmployee: configurations.ApiUrl + "/User/CreateOrUpdateEmployee",
  getGroupRights: configurations.ApiUrl + "/GetAllRightsByRoleId",
  getPurchaseIndentList: configurations.ApiUrl + "/Indent/IndentList",
  getPurchaseIndentDropDown:
    configurations.ApiUrl + "/Indent/AddIndentDropDown",
  getPurchaseIndentById: configurations.ApiUrl + "/Indent/GetIndentMasterByID",
  addPurchaseIndent: configurations.ApiUrl + "/Indent/CreateOrUpdateIndent",
  deletePurchaseIndent: configurations.ApiUrl + "/Indent/DeleteIndent",
  getPurchaseOrderList: configurations.ApiUrl + "/PO/POList",
  getPurchaseOrderDropDown: configurations.ApiUrl + "/PO/AddPODropDown",
  addPurchaseOrder: configurations.ApiUrl + "/PO/CreateOrUpdatePO",
  deletePurchaseOrder: configurations.ApiUrl + "/PO/DeletePO",
  getGRNList: configurations.ApiUrl + "/GRN/GRNList",
  getGRNDropDown: configurations.ApiUrl + "/GRN/AddGRNDropDown",
  getGRNById: configurations.ApiUrl + "/GRN/GetGRNByID",
  addGRN: configurations.ApiUrl + "/GRN/CreateOrUpdateGRN",
  deleteGRN: configurations.ApiUrl + "/GRN/DeleteGRN",
  getPurchaseBillList: configurations.ApiUrl + "/PV/PVList",
  getPurchaseBillDropDown: configurations.ApiUrl + "/PV/AddPVDropDown",
  getPurchaseBillById: configurations.ApiUrl + "/PV/GetPVMasterByID",
  addPurchaseBill: configurations.ApiUrl + "/PV/CreateOrUpdatePV",
  deletePurchaseBill: configurations.ApiUrl + "/PV/DeletePV",
};
